### PR TITLE
Handle http status 5xx error

### LINKED ISSUE #104: invalid character '<' looking for beginning of value
When validating ios receipt data, some of the receipts are failing the client.Verify call with the following error

```
invalid character '<' looking for beginning of value
```

The data is the raw base64 encoded string that the app receives.  Having passed the data through base64 decode using the following site https://www.base64decode.org/ it would appear that changing the charset from UTF-8 to ASCII means the receipt then decodes as expected, but given this is only happening for some receipts and not others I believe the issue is better fixed in this library.  

Any thoughts on what might be causing this?

### PR DESCRIPTION
**Pull request by jun06t**
resolve #104

And I defined each error because we can use ``errors.Is()`` method from go 1.13 to assert errors.
https://blog.golang.org/go1.13-errors

### CODE REVIEW

File: appstore/validator.go [hunk 1]
```diff
@@ -33,47 +34,53 @@ type Client struct {
...
 }
 
+var (
+	ErrAppStoreServer = errors.New("AppStore server error")
+
+	ErrInvalidJSON            = errors.New("The App Store could not read the JSON object you provided.")
+	ErrInvalidReceiptData     = errors.New("The data in the receipt-data property was malformed or missing.")
+	ErrReceiptUnauthenticated = errors.New("The receipt could not be authenticated.")
+	ErrInvalidSharedSecret    = errors.New("The shared secret you provided does not match the shared secret on file for your account.")
+	ErrServerUnavailable      = errors.New("The receipt server is not currently available.")
```
Comment (kitakitabauer) [inline appstore/validator.go]: I think that `receipt` is unnecessary.
The receipt server is not currently available.
↓
The server is not currently available.

Comment (jun06t) [reply appstore/validator.go]: Thanks @kitakitabauer 
These error messages are quoted from the following official document :-)

image

https://developer.apple.com/documentation/appstorereceipts/status

Comment (kitakitabauer) [reply appstore/validator.go]: I see! It's all right.
